version: '3'

services:
  bot:
    env_file: .env
    image: bot_image:latest
    build:
      context: ./bot
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 11.0.0.2
    ports:
      - "8080:8080"

  db:
    env_file: .env
    image: db_image:latest
    build:
      context: ./db
    environment:
      POSTGRES_USER: ${DB_USER}
      DB_DATABASE: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_REPL_USER: ${DB_REPL_USER}
      DB_REPL_PASSWORD: ${DB_REPL_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost all all 11.0.0.2/16 password\nhost replication replication ${DB_REPL_HOST}/16 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command:
      postgres
      -c archive_mode=on
      -c archive_command='cp %p /oracle/pg_data/archive/%f'
      -c listen_addresses='*'
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c log_replication_commands=on
    networks:
      net:
        ipv4_address: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"

  db_repl:
    env_file: .env
    image: db_repl_image:latest
    build:
      context: ./db_repl
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_REPL_USER}
      PGPASSWORD: ${DB_REPL_PASSWORD}
    command:
      bash -c "
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replications --host=${DB_HOST} --port=${DB_PORT}
      do
      echo 'Wait!'
      sleep 1s
      done
      echo 'Start!'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    depends_on:
      - db
    networks:
      net:
        ipv4_address: ${DB_REPL_HOST}
    ports:
      - "${DB_REPL_PORT}:5432"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/16
